,
                            "sales_department": "' . $sales_department . '",
                            "date": "' . $date . '",
                            "profile_name": "' . $profile_name . '",
                            "client_user_id": "' . $client_user_id . '",
                            "client_name": "' . $client_name . '",
                            "order_number": "' . $order_number . '",
                            "order_link": "' . $order_link . '",
                            "remarks": "' . $remarks . '",
                            "assigned_team": "' . $assigned_team . '",
                            "order_status": "' . $order_status . '",
                            "service_line": "' . $service_line . '",
                            "delivered_by": "' . $delivered_by . '",
                            "deli_date": "' . $deli_date . '",
                            "deli_amount": "' . $deli_amount . '",
                            "deadline": "' . $deadline . '",
                            "platform_status": "' . $platform_status . '"